version: "3.9"

services:
  proxy:
    container_name: trajectory-proxy-dev
    image: caddy:latest
    ports:
      - 80:80
    volumes:
      - ./Caddyfile-dev:/etc/caddy/Caddyfile
    networks:
      - proxy
    depends_on:
      - web
  web:
    container_name: trajectory-web-dev
    image: trajectory-web-dev
    build:
      context: ./web/
      dockerfile: ./Dockerfile-dev
    ports:
      - 35729:35729
    volumes:
      - ./web:/usr/src/trajectory-web
    networks:
      - proxy
    depends_on:
      - server
  server:
    container_name: trajectory-server-dev
    image: trajectory-server-dev
    build:
      context: ./server/
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./server:/usr/src/trajectory-server
    networks:
      - proxy
      - db
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: trajectory-db-dev
    environment:
      POSTGRES_USER: trajectory-server
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: trajectory-server
    networks:
      - db

networks:
  proxy:
  db:
