version: "3.9"

services:
  proxy:
    container_name: trajectory-proxy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy
    depends_on:
      - web
  web:
    container_name: trajectory-web
    image: trajectory-web
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    volumes:
      - ./web:/usr/src/trajectory-web
    networks:
      - proxy
    depends_on:
      - server
  server:
    container_name: trajectory-server
    image: trajectory-server
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/usr/src/trajectory-server
    networks:
      - proxy
      - db
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: trajectory-db
    environment:
      POSTGRES_USER: trajectory-server
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: trajectory-server
    networks:
      - db

networks:
  proxy:
  db:
